import {
  ArrowDownWideNarrow,
  ArrowUpWideNarrow,
  Check,
  ChevronDown,
  Clock3,
  Copy,
  File,
  FileCode2,
  FileUp,
  FolderTree,
  Hash,
  Link2,
  LogOut,
  QrCode,
  RefreshCw,
  SendHorizontal,
  Text,
  WandSparkles,
  Trash2,
  ExternalLink,
  X,
} from 'lucide-react';

export const icons = {
  close: X,
  clock: Clock3,
  copy: Copy,
  fileBadge: File,
  fileCode: FileCode2,
  file: FileUp,
  hash: Hash,
  folderTree: FolderTree,
  link: Link2,
  logout: LogOut,
  open: ExternalLink,
  qrcode: QrCode,
  refresh: RefreshCw,
  send: SendHorizontal,
  sparkles: WandSparkles,
  text: Text,
  title: ArrowDownWideNarrow,
  titleCollapse: ArrowUpWideNarrow,
  chevronDown: ChevronDown,
  check: Check,
  delete: Trash2,
};
