import {
  ArrowDownWideNarrow,
  ArrowUpWideNarrow,
  CircleAlert,
  Check,
  ChevronDown,
  Clock3,
  Copy,
  File,
  FileUp,
  FolderOpen,
  FolderTree,
  Globe,
  Hash,
  Link2,
  LogOut,
  EllipsisVertical,
  Pencil,
  QrCode,
  RefreshCw,
  SendHorizontal,
  Text,
  TextInitial,
  WandSparkles,
  Trash2,
  ExternalLink,
  X,
} from 'lucide-react';

export const icons = {
  alert: CircleAlert,
  close: X,
  clock: Clock3,
  copy: Copy,
  fileBadge: File,
  fileType: FolderOpen,
  file: FileUp,
  globe: Globe,
  hash: Hash,
  folderTree: FolderTree,
  link: Link2,
  logout: LogOut,
  more: EllipsisVertical,
  open: ExternalLink,
  qrcode: QrCode,
  refresh: RefreshCw,
  send: SendHorizontal,
  sparkles: WandSparkles,
  text: Text,
  textInitial: TextInitial,
  title: ArrowDownWideNarrow,
  titleCollapse: ArrowUpWideNarrow,
  chevronDown: ChevronDown,
  check: Check,
  delete: Trash2,
  edit: Pencil,
};
